### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by NagaSadow1938** [psiget/s2ue-docs#72]
The game launches in Russian, how can I change it to English?

**Comment by PSIget** [comment]
To enable the English language, you need to:

**For the game:**
Unpack the archive to `{game}\Windows\Stalker`(.zip) or `{game}\Stalker`(Installer) depending on the type of installation.

**For the editor:**
Unpack the file in the root directory of the type `{editor}`.
[Patch_for_Enable_English_lang.zip](https://github.com/PSIget/SonUE-Docs/files/13890553/Patch_for_Enable_English_lang.zip)
